version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: swap
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - net-swap
  db:
    image: postgres:12
    container_name: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=swapper
      - POSTGRES_DB=swapper
      - POSTGRES_PASSWORD=secret
    networks:
      - net-swap
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - app
    networks:
      - net-swap

networks:
  net-swap:
    driver: bridge
