---
- hosts: all
  become: yes
  roles:
    - docker

- hosts:
  - "machine-1"
  become: yes
  tasks:
    - name: Init a new swarm
      docker_swarm:
        state: present
        advertise_addr: "{{ hostvars['machine-1'].ansible_enp0s8.ipv4.address }}"
      register: swarm_info
    - name: Create an Overlay network
      docker_network:
        name: sms-net
        driver: overlay
        scope: swarm
        attachable: yes
        ipam_config:
          - subnet: 10.10.10.0/24

- hosts:
  - "machine-1"
  become: yes
  roles:
    - role: docker-swarm
      vars:
        type: "manager"

- hosts:
  - "machine-2"
  - "machine-3"
  become: yes
  roles:
    - role: docker-swarm
      vars:
        type: "worker"

- hosts: all
  become: yes
  vars_files:
    - vars/external_vars.yml
  tasks:
    - name: Login to Docker Hub
      docker_login:
        username: alvesluis98
        password: "{{ docker_hub_password }}"

- hosts:
  - "machine-1"
  become: yes
  vars_files:
    - vars/external_vars.yml
  tasks:
    - name: Add Mabeei secret to Swarm
      docker_secret:
        name: mabeei_key
        data: "{{ mabeei_key }}"
        state: present
      register: mabeei_secret_id
    - name: Add DockerHub password secret to Swarm
      docker_secret:
        name: docker_hub_password
        data: "{{ docker_hub_password }}"
        state: present
      register: docker_hub_secret_id
    - name: Add swap-deployer service to Swarm
      docker_swarm_service:
        name: swap-deployer
        image: alvesluis98/swap-deployer:deployer
        # should not be exposed in production
        publish:
          - published_port: 5000
            target_port: 5000
        state: present
        force_update: yes
        mounts:
          - target: '/var/run/docker.sock'
            source: '/var/run/docker.sock'
        placement:
          constraints:
            - node.role == manager
        networks:
          - sms-net
        secrets:
          - secret_name: mabeei_key
            secret_id: "{{ mabeei_secret_id.secret_id }}"
          - secret_name: docker_hub_password
            secret_id: "{{ docker_hub_secret_id.secret_id }}"
    - name: Add reverse proxy to Swarm
      docker_swarm_service:
        name: reverse-proxy
        image: alvesluis98/swap-deployer:reverse
        publish:
          - published_port: 80
            target_port: 80
        state: present
        force_update: yes
        networks:
          - sms-net
        update_config:
          delay: 10s
          parallelism: 1
        replicas: 2
