---
- hosts: all
  become: yes
  roles:
    - docker

- hosts:
  - "machine-1"
  become: yes
  tasks:
    - name: Init a new swarm
      docker_swarm:
        state: present
        advertise_addr: "{{ hostvars['machine-1'].ansible_enp0s8.ipv4.address }}"
      register: swarm_info
    - name: Create an Overlay network
      docker_network:
        name: sms-net
        driver: overlay
        scope: swarm
        attachable: yes
        ipam_config:
          - subnet: 10.10.10.0/24

- hosts:
  - "machine-1"
  become: yes
  roles:
    - role: docker-swarm
      vars:
        type: "manager"

- hosts:
  - "machine-2"
  - "machine-3"
  become: yes
  roles:
    - role: docker-swarm
      vars:
        type: "worker"

- hosts:
  - "machine-1"
  become: yes
  tasks:
    - name: Login to Docker Hub
      docker_login:
        username: alvesluis98
        password: # fill in this gap
    - name: Add swap-deployer service to Swarm
      docker_swarm_service:
        name: swap-deployer
        image: alvesluis98/swap-deployer:0.1
        # should not be exposed in production
        publish:
          - published_port: 5000
            target_port: 5000
        state: present
        force_update: yes
        mounts:
          - target: '/var/run/docker.sock'
            source: '/var/run/docker.sock'
        placement:
          constraints:
            - node.role == manager
