---
- name: Copy Swap image files
  copy:
    src: ./swap/
    dest: /opt/swap
- name: Copy Dockerfile, entrypoint and wait
  copy:
    src: "{{ item }}"
    dest: /opt
  loop:
    - ./entrypoint.sh
    - ./wait-for-it.sh
    - ./dev.Dockerfile
- name: Add Swap image to local registry
  docker_image:
    name: swap
    tag: "0.1"
    source: build
    build:
      path: /opt
      pull: no
      dockerfile: dev.Dockerfile
    force_tag: yes
    state: present
    force_source: no # SHOULD PROBABLY BE YES, temporarily no just to save time :3