---
- name: Copy flask image files
  copy:
    src: ./flask_app/
    dest: /opt/flask_app
- name: Add Flask image to local registry
  docker_image:
    name: flask
    tag: "0.1"
    source: build
    build:
      path: /opt/flask_app
      pull: no
    force_tag: yes
    state: present
    force_source: yes